// Generated by https://quicktype.io

import { Character } from "./allCharactersInterface";

export interface AllClanes {
    clans:       Clan[];
}

export interface Clan {
    id:         number;
    name:       string;
    characters: Character[];
}

