// Generated by https://quicktype.io

export interface BijuResponse {
    tailedBeasts:      TailedBeast[];
}

export interface TailedBeast {
    id:            number;
    name:          string;
    images:        string[];
    debut:         Debut2;
    jutsu:         string[];
    natureType?:   string[];
    personal:      Personal2;
    uniqueTraits?: string[];
    voiceActors?:  VoiceActors2;
    tools?:        string[];
}

export interface Debut2 {
    manga:     string;
    anime:     string;
    game:      string;
    ova?:      string;
    appearsIn: AppearsIn;
}

export enum AppearsIn {
    AnimeMangaNovelGameMovie = "Anime, Manga, Novel, Game, Movie",
}


export interface Personal2 {
    status?:        string;
    kekkeiGenkai?:  string;
    classification: string[] | string;
    jinchūriki:     string[];
    titles?:        string[];
    species?:       string;
    affiliation?:   string[] | string;
}

export interface VoiceActors2 {
    japanese: string;
    english:  string[] | string;
}
