// Generated by https://quicktype.io

import { Character } from "./allCharactersInterface";

export interface KekkeiGenkaiResponse {
    kekkeigenkai:      Kekkeigenkai[];
    currentPage:       number;
    pageSize:          number;
    totalKekkeiGenkai: number;
}

export interface Kekkeigenkai {
    id:         number;
    name:       string;
    characters: Character[];
}


